echo "Xor.tst"
HardwareSimulator Xor.tst
echo "Or.tst"
HardwareSimulator Or.tst
echo "Or8Way.tst"
HardwareSimulator Or8Way.tst
echo "Or16.tst"
HardwareSimulator Or16.tst
echo "Not.tst"
HardwareSimulator Not.tst
echo "Not16.tst"
HardwareSimulator Not16.tst
echo "Mux.tst"
HardwareSimulator Mux.tst
echo "Mux8Way16.tst"
HardwareSimulator Mux8Way16.tst
echo "Mux4Way16.tst"
HardwareSimulator Mux4Way16.tst
echo "Mux16.tst"
HardwareSimulator Mux16.tst
echo "DMux.tst"
HardwareSimulator DMux.tst
echo "DMux8Way.tst"
HardwareSimulator DMux8Way.tst
echo "DMux4Way.tst"
HardwareSimulator DMux4Way.tst
echo "And.tst"
HardwareSimulator And.tst
echo "And16.tst"
HardwareSimulator And16.tst
